package com.media.entities;

// Generated 2009-9-25 11:55:31 by Hibernate Tools 3.2.2.GA


/**
 * Dictionary generated by hbm2java
 */
public class Dictionary implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private String dictionaryid;
  private String typenameen;
  private String typenamecn;
  private String typeisauth;
  private String typeisvisible;
  private String typetype;
  private String typestatus;
  private String createtime;
  private String lastmodtime;
  private String lastmodusr;

  public Dictionary() {
    
  }

  public Dictionary(String dictionaryid, String typenameen,
      String typenamecn, String typetype) {
    this.dictionaryid = dictionaryid;
    this.typenameen = typenameen;
    this.typenamecn = typenamecn;
    this.typetype = typetype;
  }

  public Dictionary(String dictionaryid, String typenameen,
      String typenamecn, String typeisauth, String typeisvisible,
      String typetype, String typestatus, String createtime,
      String lastmodtime, String lastmodusr) {
    this.dictionaryid = dictionaryid;
    this.typenameen = typenameen;
    this.typenamecn = typenamecn;
    this.typeisauth = typeisauth;
    this.typeisvisible = typeisvisible;
    this.typetype = typetype;
    this.typestatus = typestatus;
    this.createtime = createtime;
    this.lastmodtime = lastmodtime;
    this.lastmodusr = lastmodusr;
  }

  public String getDictionaryid() {
    return this.dictionaryid;
  }

  public void setDictionaryid(String dictionaryid) {
    this.dictionaryid = dictionaryid;
  }

  public String getTypenameen() {
    return this.typenameen;
  }

  public void setTypenameen(String typenameen) {
    this.typenameen = typenameen;
  }

  public String getTypenamecn() {
    return this.typenamecn;
  }

  public void setTypenamecn(String typenamecn) {
    this.typenamecn = typenamecn;
  }

  public String getTypeisauth() {
    return this.typeisauth;
  }

  public void setTypeisauth(String typeisauth) {
    this.typeisauth = typeisauth;
  }

  public String getTypeisvisible() {
    return this.typeisvisible;
  }

  public void setTypeisvisible(String typeisvisible) {
    this.typeisvisible = typeisvisible;
  }

  public String getTypetype() {
    return this.typetype;
  }

  public void setTypetype(String typetype) {
    this.typetype = typetype;
  }

  public String getTypestatus() {
    return this.typestatus;
  }

  public void setTypestatus(String typestatus) {
    this.typestatus = typestatus;
  }

  public String getCreatetime() {
    return this.createtime;
  }

  public void setCreatetime(String createtime) {
    this.createtime = createtime;
  }

  public String getLastmodtime() {
    return this.lastmodtime;
  }

  public void setLastmodtime(String lastmodtime) {
    this.lastmodtime = lastmodtime;
  }

  public String getLastmodusr() {
    return this.lastmodusr;
  }

  public void setLastmodusr(String lastmodusr) {
    this.lastmodusr = lastmodusr;
  }

}
